// Collects the licences of everything that ends up inside the app.
//
//   node Support/licences.mjs
//
// Run by build.sh, so the notices cannot drift from what is actually bundled.
// This is not paperwork: highlight.js is BSD-3-Clause, which requires its
// copyright notice to travel with any binary you hand to somebody.
//
// Writes THIRD-PARTY.md for the repository and Support/Credits.html for the
// app bundle — macOS shows the latter in the standard About panel on its own,
// with no code on our side.

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const modules = path.join(root, 'renderer', 'node_modules')

/// The packages esbuild actually pulled in, read from the metafile it writes
/// on every build. Walking node_modules instead would credit 122 packages when
/// the bundle contains a fraction of that — generous, but not true.
function bundled() {
  const meta = path.join(root, 'renderer', '.esbuild-meta.json')
  if (!fs.existsSync(meta)) return null

  const names = new Set()
  for (const input of Object.keys(JSON.parse(fs.readFileSync(meta, 'utf8')).inputs)) {
    const at = input.lastIndexOf('node_modules/')
    if (at < 0) continue
    const rest = input.slice(at + 'node_modules/'.length).split('/')
    names.add(rest[0].startsWith('@') ? `${rest[0]}/${rest[1]}` : rest[0])
  }
  return names
}

const inBundle = bundled()

/// Every package reachable from node_modules, scoped ones included.
function* packages(dir) {
  for (const entry of fs.readdirSync(dir)) {
    if (entry.startsWith('.')) continue
    const full = path.join(dir, entry)
    if (entry.startsWith('@')) {
      yield* packages(full)
      continue
    }
    const manifest = path.join(full, 'package.json')
    if (fs.existsSync(manifest)) yield { dir: full, manifest }
  }
}

const LICENCE_FILES = ['LICENSE', 'LICENSE.md', 'LICENSE.txt', 'LICENCE', 'COPYING', 'UNLICENSE']

function licenceText(dir) {
  for (const name of LICENCE_FILES) {
    const full = path.join(dir, name)
    if (fs.existsSync(full)) return cleanText(fs.readFileSync(full, 'utf8'))
  }
  return ''
}

// Third-party notices sometimes carry spaces at line ends. They have no legal
// meaning and make the generated files fail the repository's whitespace check.
function cleanText(text) {
  return text.trim().replace(/[ \t]+$/gm, '')
}

const found = new Map()
for (const { dir, manifest } of packages(modules)) {
  const meta = JSON.parse(fs.readFileSync(manifest, 'utf8'))
  if (!meta.name) continue
  if (inBundle && !inBundle.has(meta.name)) continue
  const licence = typeof meta.license === 'string' ? meta.license : meta.license?.type
  // Keyed by name only: a duplicated version is the same licence.
  if (!found.has(meta.name)) {
    found.set(meta.name, {
      name: meta.name,
      version: meta.version ?? '',
      licence: licence ?? 'see text',
      url: meta.homepage ?? meta.repository?.url?.replace(/^git\+|\.git$/g, '') ?? '',
      text: licenceText(dir),
    })
  }
}

// Sparkle arrives as a binary Swift package rather than through node_modules,
// but its notice has exactly the same obligation to travel with the app. Read
// the version SwiftPM resolved and the licence bundled beside the artifact.
const resolvedFile = path.join(root, 'Package.resolved')
const sparkleLicence = path.join(root, '.build', 'artifacts', 'sparkle', 'Sparkle', 'LICENSE')
if (fs.existsSync(resolvedFile) && fs.existsSync(sparkleLicence)) {
  const pins = JSON.parse(fs.readFileSync(resolvedFile, 'utf8')).pins ?? []
  const sparkle = pins.find((pin) => pin.identity === 'sparkle')
  found.set('Sparkle', {
    name: 'Sparkle',
    version: sparkle?.state?.version ?? '',
    licence: 'MIT and permissive bundled licences',
    url: 'https://github.com/sparkle-project/Sparkle',
    text: cleanText(fs.readFileSync(sparkleLicence, 'utf8')),
  })
}

const list = [...found.values()].sort((a, b) => a.name.localeCompare(b.name))

/// A licence file is somebody else's markdown and may contain fences of its
/// own. Fence it with one backtick more than the longest run inside it, or the
/// rest of the document silently stops being code.
function fenced(text) {
  const longest = Math.max(2, ...[...text.matchAll(/`+/g)].map((m) => m[0].length))
  const fence = '`'.repeat(longest + 1)
  return `${fence}\n${text}\n${fence}`
}

/* ------------------------------------------------------------------- repo */

const markdown = `# Third-party licences

Imark bundles the packages below into the application. Every one of them is
permissive — there is no copyleft anywhere in the tree — but several require
their copyright notice to travel with the binary, which is what this file is
for. It is generated by \`Support/licences.mjs\` and rebuilt on every build; do
not edit it by hand.

${list.length} packages${inBundle ? '' : ' (everything in node_modules — build the renderer first for the exact list)'}: ${[...new Set(list.map((p) => p.licence))].sort().join(', ')}.

${list
  .map(
    (p) => `## ${p.name} ${p.version}

${p.licence}${p.url ? ` · ${p.url}` : ''}

${p.text ? fenced(p.text) : '_No licence text shipped with the package._'}`,
  )
  .join('\n\n')}
`

fs.writeFileSync(path.join(root, 'THIRD-PARTY.md'), markdown)

/* ------------------------------------------------------------------- app */

const escape = (s) =>
  String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')

const credits = `<!doctype html>
<meta charset="utf-8">
<style>
  body { font: 12px -apple-system, sans-serif; margin: 0; color: -apple-system-label; }
  h2 { font-size: 12px; margin: 14px 0 2px; }
  p { margin: 0 0 2px; color: -apple-system-secondaryLabel; }
  pre { font: 10px ui-monospace, Menlo, monospace; white-space: pre-wrap;
        color: -apple-system-tertiaryLabel; margin: 0 0 6px; }
</style>
<p>Imark bundles these, all under permissive licences.</p>
${list
  .map(
    (p) => `<h2>${escape(p.name)} ${escape(p.version)}</h2>
<p>${escape(p.licence)}</p>
${p.text ? `<pre>${escape(p.text)}</pre>` : ''}`,
  )
  .join('\n')}
`

fs.writeFileSync(path.join(root, 'Support', 'Credits.html'), credits)

console.log(`licenças → THIRD-PARTY.md e Support/Credits.html (${list.length} pacotes)`)
